myproject/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path('', views.homepage),
    path('about/', views.about),
    path('site2/', views.site2),
    path('posts/', include('posts.urls')),
    path('users/', include('users.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.posts_list, name="list"),
    path('new-post/', views.post_new, name="new-post"),
    path('<slug:slug>', views.post_page, name="page"),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register_view, name="register"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout")
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=75)
    body = models.TextField()
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)
    banner = models.ImageField(default='fallback.png', blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.title

users/models.py
from django.db import models

# Create your models here.

posts/forms.py
from django import forms
from . import models

class CreatePost(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = ['title', 'body', 'slug', 'banner']

myproject/views.py
#from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    #return HttpResponse("Hello World! I'm home")
    return render(request, "home.html")

def about(request):
    #return HttpResponse("My About page.")
    return render(request, "about.html")

def site2(request):
    #return HttpResponse("My About page.")
    return render(request, "site2.html")

posts/views.py
from django.shortcuts import render, redirect
from .models import Post
from django.contrib.auth.decorators import login_required
from . import forms

# Create your views here.

def posts_list(request):
    posts = Post.objects.all().order_by('-date')
    return render(request, 'posts/posts_list.html', {'posts': posts})

def post_page(request, slug):
    post = Post.objects.get(slug=slug)
    return render(request, 'posts/post_page.html', {'post': post})

@login_required(login_url="/users/login/")
def post_new(request):
    if request.method == "POST":
        form = forms.CreatePost(request.POST, request.FILES)
        if form.is_valid():
            newpost = form.save(commit=False)
            newpost.author = request.user
            newpost.save()
            return redirect("posts:list")
    else:
        form = forms.CreatePost()
    return render(request, 'posts/post_new.html', {'form': form})

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
# Create your views here.

def register_view(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            login(request, form.save())
            return redirect("posts:list")
    else:
        form = UserCreationForm
    return render(request, "users/register.html", { "form": form })

def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            login(request, form.get_user())
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect("posts:list")
    else:
        form = AuthenticationForm()
    return render(request, "users/login.html", {"form": form})

def logout_view(request):
    if request.method == "POST":
        logout(request)
        return redirect("posts:list")

posts/templates/posts/post_new.html
{% extends 'layout.html' %}

{% block title %}
    New Post
{% endblock %}

{% block content %}
<section>
    <h1>New Post</h1>
    <form class="form-with-validation" action="{% url 'posts:new-post' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <button class="form-submit">Add post</button>
    </form>
</section>
{% endblock %}

posts/templates/posts/post_page.html
{% extends 'layout.html' %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block content %}
  <section>
      <img class="banner"
           src="{{ post.banner.url }}"
           alt ="{{ post.title }}"
       />
      <h1>{{ post.title }}</h1>
      <p>{{ post.date }}</p>
      <p>{{ post.body }}</p>
  </section>
{% endblock %}

posts/templates/posts/posts_list.html
{% extends 'layout.html' %}

{% block title %}
    Posts
{% endblock %}

{% block content %}
<section>
    <h1>Posts</h1>
    {% for post in posts %}
    <article class="post">
        <h2>
            <a href="{% url 'posts:page' slug=post.slug %}">
               {{ post.title }}
            </a>

        </h2>
        <p>{{ post.date }} by {{ post.author}}</p>
        <p>{{ post.body }}</p>
    </article>
    {% endfor %}
</section>
{% endblock %}

templates/about.html
{% extends 'layout.html' %}

{% block title %}
    About
{% endblock %}

{% block content %}
    <h1>About</h1>
  <p>Check out my <a href="/">Main</a> page.</p>
{% endblock %}

<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About</title>
    <link rel="stylesheet" href="{% static 'css/style2.css' %}">
    <script src ="{% static 'js/main.js' %}" defer></script>
</head>
<body>
  <h1>Home</h1>
  <p>Check out my <a href="/">Main</a> page.</p>
</body>
</html>

templates/home.html
{% extends 'layout.html' %}

{% block title %}
    Home
{% endblock %}

{% block content %}
  <h1>Home</h1>
  <p>Check out my <a href="/about">About</a> page.</p>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
      {% block title %}
        Django App
      {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src ="{% static 'js/main.js' %}" defer></script>
</head>
<body>
  <nav>
    <a href="/"><span role="img" aria-label="Home" title="Домашняя страница">🏠</span></a> |
    <a href="/about">🤔</a> |
    <a href="{% url 'posts:list' %}">📰</a> |
    <a href="/site2">🌍</a> |
      {% if user.is_authenticated %}
        <a href="{% url 'posts:new-post' %}"><span role="img" aria-label="New Post" title="New Post">✒️</span></a> |
        <form class="logout" action="{% url 'users:logout' %}" method="post">
        {% csrf_token %}
        <button class="logout-button" aria-label="User logout" title="User logout">👋🏻👋🏻</button>
        </form> |
      {% else %}
        <a href="{% url 'users:register' %}">🧑🏻</a> |
        <a href="{% url 'users:login' %}">🔒</a> |
      {% endif %}
  </nav>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

templates/site2.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
    <link rel="stylesheet" href="{% static 'css/site2.css' %}">
</head>
<body>
  <header class="header">
  <div class="container">
    <img src="https://netology-code.github.io/html-2-diploma/sources/images/noemi-logo.svg" class="header-logo" alt="NOEMI">
    <nav class="menu">
      <ul class="menu-list">
        <li class="menu-list-item">
          <a class="menu-link" href="/">Главная</a>
        </li>
        <li class="menu-list-item">
          <a class="menu-link" href="#0">Посты</a>
        </li>
        <li class="menu-list-item">
          <a class="menu-link" href="#0">Статьи</a>
        </li>
        <li class="menu-list-item">
          <a class="menu-link" href="#0">Теги</a>
        </li>
        <li class="menu-list-item">
          <a class="menu-link" href="#0">Темы</a>
        </li>
        <li class="menu-list-item">
          <a class="menu-link" href="#0">Контакты</a>
        </li>
      </ul>
    </nav>
     <h1 class="header-title" #style="color: #ffffff">Блог о творчестве, спорте и образе жизни</h1>
  </div>
</header>
<div class="container">
<main class="courses">
  <article class="course">
      <img class="course-img"
           src="https://netology-code.github.io/html-2-diploma/sources/images/last-post1.jpg"
           alt="Утренний пляж">
    <div class="course-info">
      <ul class="course-tag-list">
        <li class="course-tag"><a href="#" class="course-tag-link">Travel</a></li>
        <li class="course-tag"><a href="#" class="course-tag-link">Health</a></li>
      </ul>
      <h2 class="course-name"><a href="#" class="course-link">10 мест, ради которых стоит проснуться на рассвете</a>
      </h2>
      <time class="article-date" datetime="2019-06-10">10 июня 2019</time><span class="author">неизвестный автор</span>
      <div class="course-description">
        <p>
          Итак, вы в Питере. Раннее утро. Лед с рек и каналов уже ушел, запущены фонтаны города… Музеи еще закрыты. Что посмотреть?
        </p>
      </div>
    </div>
  </article>
  <article class="course">
    <img class="course-img"
           src="https://netology-code.github.io/html-2-diploma/sources/images/last-post2.jpg"
           alt="Йога на пляже">
    <div class="course-info">
      <ul class="course-tag-list">
        <li class="course-tag"><a href="#" class="course-tag-link">Health</a></li>
        <li class="course-tag"><a href="#" class="course-tag-link">Lifestyle</a></li>
      </ul>
      <h2 class="course-name"><a href="#" class="course-link">Йога для начинающих в домашних условиях</a></h2>
      <time class="article-date" datetime="2019-06-10">10 июня 2019</time><span class="author">неизвестный автор</span>
      <div class="course-description">
        <p>
         Расскажем, какие упражнения выбрать и как сделать коврик для занятий йогой из того, что можно найти в шкафу.
        </p>
      </div>
    </div>
  </article>
  <article class="course">
    <img class="course-img"
           src="https://netology-code.github.io/html-2-diploma/sources/images/last-post3.jpg"
           alt="Концерт на улице">
    <div class="course-info">
       <ul class="course-tag-list">
        <li class="course-tag"><a href="#" class="course-tag-link">Music</a></li>
      </ul>
      <h2 class="course-name"><a href="#" class="course-link">Лучшие музыкальные фестивали этого лета</a></h2>
      <time class="article-date" datetime="2019-06-10">10 июня 2019</time><span class="author">неизвестный автор</span>
      <div class="course-description">
        <p>Лето на носу, а с ним и музыкальные фестивали. На каком же из них вы разобъете свою палатку?</p>
        <p>Мы составили список лучших летних фестивалей по всему миру.</p>
      </div>
    </div>
  </article>
  <article class="course">
    <img class="course-img"
           src="https://netology-code.github.io/html-2-diploma/sources/images/last-post4.jpg"
           alt="Еда">
    <div class="course-info">
       <ul class="course-tag-list">
        <li class="course-tag"><a href="#" class="course-tag-link">Lifestyle</a></li>
        <li class="course-tag"><a href="#" class="course-tag-link">Food</a></li>
       </ul>
       <h2 class="course-name"><a href="#" class="course-link">Наукоёмкий подход к кулинарии</a></h2>
       <time class="article-date" datetime="2019-06-10">10 июня 2019</time><span class="author">неизвестный автор</span>
       <div class="course-description">
        <p>
          Узнаем основы проектирования новых пищевых и около-пищевых опытов, вскроем физику, химию и микробиологию еды.
        </p>
      </div>
    </div>
  </article>
  <article class="course">
    <img class="course-img"
           src="https://netology-code.github.io/html-2-diploma/sources/images/last-post5.jpg"
           alt="Подушка">
    <div class="course-info">
       <ul class="course-tag-list">
        <li class="course-tag"><a href="#" class="course-tag-link">Lifestyle</a></li>
        <li class="course-tag"><a href="#" class="course-tag-link">interior</a></li>
        <li class="course-tag"><a href="#" class="course-tag-link">art</a></li>
      </ul>
      <h2 class="course-name"><a href="#" class="course-link">Делаем модные принты на подушках для интерьера</a></h2>
      <time class="article-date" datetime="2019-06-10">10 июня 2019</time>
      <div class="course-description">
        <p>
          Подушки для дивана целесообразнее заказать в съемных чехлах на молнии, если потребуется чистка подушек, проще снять чехлы, чем везти подушку в химчистку
        </p>
      </div>
    </div>
  </article>
  <article class="course">
    <img class="course-img"
           src="https://netology-code.github.io/html-2-diploma/sources/images/last-post6.jpg"
           alt="Горный спорт">
    <div class="course-info">
      <ul class="course-tag-list">
        <li class="course-tag"><a href="#" class="course-tag-link">Travel</a></li>
        <li class="course-tag"><a href="#" class="course-tag-link">lifestyle</a></li>
      </ul>
      <h2 class="course-name"><a href="#" class="course-link">Как первый раз отправиться в горы?</a></h2>
      <time class="article-date" datetime="2019-06-10">10 июня 2019</time><span class="author">неизвестный автор</span>
      <div class="course-description">
        <p>
          Для начала нужно определиться, в каком формате пройдёт ваше путешествие. Это зависит от многих факторов, не только ваших желаний и интересов.
        </p>
      </div>
    </div>
  </article>
  <article class="course">
    <img class="course-img"
           src="https://netology-code.github.io/html-2-diploma/sources/images/last-post4.jpg"
           alt="Еда">
    <div class="course-info">
      <ul class="course-tag-list">
        <li class="course-tag"><a href="#" class="course-tag-link">Lifestyle</a></li>
        <li class="course-tag"><a href="#" class="course-tag-link">food</a></li>
      </ul>
      <h2 class="course-name"><a href="#" class="course-link">Наукоёмкий подход к кулинарии</a></h2>
      <time class="article-date" datetime="2019-06-10">10 июня 2019</time><span class="author">неизвестный автор</span>
      <div class="course-description">
        <p>
          Узнаем основы проектирования новых пищевых и около-пищевых опытов, вскроем физику, химию и микробиологию еды.
        </p>
      </div>
    </div>
  </article>
</main>
<aside>
  <section class="new-posts">
    <h2 class="new-post-title">Новые посты</h2>
    <article class="last-post">
    <img class="last-post-preview" src="https://netology-code.github.io/html-2-diploma/sources/images/2.jpg" alt="Утренний пляж">
    <div class="last-post-header">
    <time class="last-post-date" datetime="2022-06-14">14 июня 2019</time>
			<h2 class="last-post-title">
			<a href="#" class="last-post-link">10 мест, ради которых стоит проснуться</a>
			</h2>
    </div>
   </article>
    <article class="last-post">
    <img class="last-post-preview" src="https://netology-code.github.io/html-2-diploma/sources/images/151.jpg" alt="Йога на пляже">
		<div class="last-post-header">
      <time class="last-post-date" datetime="2022-06-14">14 июня 2019</time>
			<h2 class="last-post-title">
        <a href="#" class="last-post-link">Йогда для домашних</a>
			</h2>
		</div>
   </article>
    <article class="last-post">
    <img class="last-post-preview" src="https://netology-code.github.io/html-2-diploma/sources/images/45.jpg" alt="Кресло и пианино">
		<div class="last-post-header">
      <time class="last-post-date" datetime="2022-06-14">14 июня 2019</time>
			<h2 class="last-post-title">
				<a href="#" class="last-post-link">Как мы превратили классное место в балкон</a>
			</h2>
		</div>
    </article>
    <article class="last-post">
      <img class="last-post-preview" src="https://netology-code.github.io/html-2-diploma/sources/images/501.jpg" alt="Еда">
      <div class="last-post-header">
        <time class="last-post-date" datetime="2022-06-14">14 июня 2019</time>
				<h2 class="last-post-title">
          <a href="#" class="last-post-link">Кулинарный подход к науке</a>
				</h2>
			</div>
    </article>
    <article class="last-post">
      <img class="last-post-preview" src="https://netology-code.github.io/html-2-diploma/sources/images/7.jpg" alt="Девушки с длинными волосами">
			<div class="last-post-header">
        <time class="last-post-date" datetime="2022-06-14">14 июня 2019</time>
				<h2 class="last-post-title">
          <a href="#" class="last-post-link">Лучшие прически для распущенных волос</a>
				</h2>
			</div>
    </article>
  </section>
  <section class="search">
    <form class="search-form">
      <input class="search-field" name="query" placeholder="Найти..." id="search-field" required>
      <label for="search-field"><span class="visually-hidden">Поле поиска</span></label>
    <button class="search-button" id="search-button"><span class="visually-hidden">Кнопка поиска</span></button>
      <label for="search-button"></label>
    </form>
  </section>
  <section class="subscribe">
    <h2 class="subscribe-title">Рассылка</h2>
    <form class="subscribe-form">
    <label for="subscribe-field">
      <span class="visually-hidden">Кликни меня!</span>
      <input class="subscribe-field" type="email" placeholder="Ваш email-адрес" required>
    </label>
    <button class="subscribe-button">Подписаться</button>
    </form>
  </section>
  <section class="tags">
    <h2 class="tags-title">Теги</h2>
    <ul class="tag-list">
      <li class="tag-list-item">
        <a href="#" class="tag">fashion</a>
      </li>
      <li class="tag-list-item">
        <a href="#" class="tag">music</a>
      </li>
      <li class="tag-list-item">
        <a href="#" class="tag">lifestyle</a>
      </li>
      <li class="tag-list-item">
        <a href="#" class="tag">art</a>
      </li>
      <li class="tag-list-item">
        <a href="#" class="tag">interior</a>
      </li>
      <li class="tag-list-item">
        <a href="#" class="tag">travel</a>
      </li>
      <li class="tag-list-item">
        <a href="#" class="tag">food</a>
      </li>
      <li class="tag-list-item">
        <a href="#" class="tag">health</a>
      </li>
    </ul>
  </section>
  <section class="categories">
    <h3 class="category-title">Темы</h3>
    <ul class="category-list">
      <li class="category-list-item" style="border: none"><a href="#" class="category-list-link">Красота</a><sup class="category-count">12</sup></li>
      <li class="category-list-item"><a href="#" class="category-list-link">Здоровье</a><sup class="category-count">4</sup></li>
      <li class="category-list-item"><a href="#" class="category-list-link">Образ жизни</a><sup class="category-count">145</sup></li>
      <li class="category-list-item"><a href="#" class="category-list-link">Музыка</a><sup class="category-count">28</sup></li>
      <li class="category-list-item"><a href="#" class="category-list-link">Спорт</a><sup class="category-count">62</sup></li>
      <li class="category-list-item"><a href="#" class="category-list-link">Йога</a><sup class="category-count">8</sup></li>
    </ul>
  </section>
</aside>
<footer>
  <div class="contacts">
    <ul class="contacts-list">
      <li><a href="#" class="dribble"><span class="visually-hidden">Dribble</span></a></li>
      <li><a href="#" class="pinterest"><span class="visually-hidden">Pinterest</span></a></li>
      <li><a href="#" class="tumblr"><span class="visually-hidden">Tubmlr</span></a></li>
    </ul>
  </div>
  <div class="copyright">
     <span class="copyright"><a href="#" class="copyright-link">Copyright © 2009–2019 City Blog LLC.</a></span>
  </div>
</footer>
</div>
</body>
</html>

users/templates/users/login.html
{% extends 'layout.html' %}

{% block title %}
    Log in
{% endblock %}

{% block content %}
  <h1>Log in</h1>
    <form class="form-with-validation" action="{% url 'users:login' %}" method="post">
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}"/>
        {% endif %}
        <button class="form-submit">Submit</button>
    </form>
{% endblock %}

users/templates/users/register.html
{% extends 'layout.html' %}

{% block title %}
    Register a New User
{% endblock %}

{% block content %}
  <h1>Register a New User</h1>
    <form class="form-with-validation" action="{% url 'users:register' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <button class="form-submit">Submit</button>
    </form>
{% endblock %}